### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by AdrianoRamalho21** [RobertGrubb/tiktok-php#13]
Hello there :)

So, here's the deal, I was trying to access a video with a invalid ID, and it crashed with the following error:
"Class 'TikTok\Core\Models\Exception' not found"

I went to the scraper folder on vendor, and there is no "Exception" file in the "Models" folder, I had to create one manually to catch the exception and skip it.

Maybe more people have the same issue...
I think it requires a fix from you, ma man, so we can update it through composer ;)

Give me some feedback when u get this ;)

**Comment by RobertGrubb** [comment]
Hi there! I will have an update for this most likely tomorrow! Thank you for finding the bug!

**Comment by RobertGrubb** [comment]
Hey there! 

This has been updated in `v1.7.0` which was just published about 2 minutes ago. Give it some time for packagist cdn to catch up, but update at your earliest convenience and this issue will be taken care of.

*NOTE* This will no longer be caught in an exception and will be returned within the `$scraper->error` property. (The original method called (`$scraper->user->video()`) will now return false).

```
use TikTok\Scraper;
$scraper = new Scraper();

try {
  $data = $scraper->user->video('iratee', 6821468282583928023);
  if ($scraper->error) print_r($scraper->error);
  print_r($data);
} catch (Exception $e) {
  echo $e->getMessage() . PHP_EOL;
}
```

Above is an example of a non-existent video.
