### ISSUE TITLE
Video url without watermark is not coming

### ISSUE THREAD

**Issue by sarabhi92git** [RobertGrubb/tiktok-php#16]
Hi,

I am not getting video url without watermark

**Comment by sarabhi92git** [comment]
You may check this url, it is giving video vithout watermark
https://snaptik.app/

Please add video url without watermark in your API.
Thank you in Advance!

**Comment by sarabhi92git** [comment]
Any update on it? @RobertGrubb

**Comment by RobertGrubb** [comment]
Looking into this tonight.

**Comment by RobertGrubb** [comment]
This is fixed as of `v1.7.3`
