### ISSUE TITLE
How can I create a Proxy to set in the API, please help

### ISSUE THREAD

**Issue by sarabhi92git** [RobertGrubb/tiktok-php#18]
Hi @RobertGrubb , 

I want to create my own proxy to use in the API, May I know which software you have used to create the proxy you had provided me for testing purpose.

I need to create my own proxy. I am running Ubuntu Server for hosting API source code.

Please help me!

Thank You in Advance!

**Comment by RobertGrubb** [comment]
I don't have any insight into creating a proxy. I usually use proxy rotators and what not. My best advice is to google how to do so and go from there. I apologize for not being more a help on this one.
