### ISSUE TITLE
Your Scrapper not giving results for All Videos data by user

### ISSUE THREAD

**Issue by sarabhi92git** [RobertGrubb/tiktok-php#20]
Your Scrapper not giving results for All Videos data by user

Previously it was working but now it is not giving data. I have tested using changing the IP but still not giving data.
I am running all-videos.php of your example file

**Comment by sarabhi92git** [comment]
Getting this in response code

{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"LvW02MqgVpBjcARrOkYOgA370kGo7LsGttk3*Ie4bIUk2z6HN9Mo244P*dMK7KihKx3pEC1R2BrwcAfxrD80FhvGZDcA4uHbh6hWPHEwstg9Z0BMk7guDRExTEq7ri4VfRaoMHYDswzGwvTy6mDfF0kSrn3bCPCYYhE4ZVCIIAdqmylROu5G2mWExGBWDFdLldTj5lFF4rEJ4QP8LsF4rTT6EKhRqE8.","verify_event":"","fp":"verify_b1d33cb8ea39af4cce97411c04b15dbe"}

**Comment by RobertGrubb** [comment]
Yeah, it's a captcha response that is being seen more and more. 

I've released a new version `1.7.3` that changes from the `m.` route to the `www.` route where I've been seeing less of these responses until a real fix is in place. Let me know if that works out.

**Comment by RobertGrubb** [comment]
Going to close this for now. If it comes up again, please reopen.
