### ISSUE TITLE
API not giving all videos data

### ISSUE THREAD

**Issue by sarabhi92git** [RobertGrubb/tiktok-php#22]
When I try to fetch a user's all videos, the users have 2900 videos but API is not giving all videos.

Sometimes it gives only 250 videos and sometimes it gives only 550 and sometimes it gives nothing.

I tried many times by changing the IP but the same thing happens.

I think API is failing in getting all videos of users.
I run the all-videos.php in your API example folder

**Comment by RobertGrubb** [comment]
Alrighty, I can look into it. It's possible that they are limiting the requests. It may require me placing a sleep on the method.

I'll find some time tonight to test it. 

Thanks.

**Comment by sarabhi92git** [comment]
Thank you @RobertGrubb for your response!

**Comment by RobertGrubb** [comment]
Have not forgot about this, however broken video downloads took priority over this. Will circle back.

**Comment by RobertGrubb** [comment]
This comes down to the main issue that we're facing while scraping TikTok, which is captcha being returned. 

Once we get that portion fixed, all tickets regarding that will be solved. Closing this as this issue is the main focus.
