### ISSUE TITLE
Video URL Without Watermark returning null on downloadVideo.php

### ISSUE THREAD

**Issue by sarabhi92git** [RobertGrubb/tiktok-php#23]
Hi,

Video URL Without Watermark returning null on downloadVideo.php

API not working to download video without watermark.

**Comment by RobertGrubb** [comment]
This is a known issue, however, because of them changing all of their cdn data, I will need to wait until they're finished before I can properly provide a correct solution for this. More to come soon! Keep following the version deployments, and I will make sure to include it in the title.
