### ISSUE TITLE
VideoUrls stopped working completly

### ISSUE THREAD

**Issue by AdrianoRamalho21** [RobertGrubb/tiktok-php#24]
Hello once again Robert :)

So, this time, it seems the problem is about tiktok itself and not the scrapper :D
When I get the information about a tiktok video through your scrapper, all videoUrls are "broken", for example:

[https://v19-web-newkey.tiktokcdn.com/8e78a0cb9e1980f5811b87dbbfdf311f/5f6b6ae9/video/tos/alisg/tos-alisg-pve-0037c001/12c438f5c72c44cd9f2a061538800157/?a=1988&br=2570&bt=1285&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202009230933500101902080120F00080D&lr=tiktok_m&mime_type=video_mp4&qs=0&rc=M3czOGhlPDY5dzMzMzczM0ApNDw7aTY4PDs0Nzk2OGloNGduMnE2MDQxamlfLS1iMTRzczJhMWFgXl5fXl4uLjEwLTM6Yw%3D%3D&vl=&vr=](url)

After some research, I found out that some people are having the same issue with other tiktok scrappers and some of them are saying tiktok has changed their network security around embbed videos, although, all thumbnails work as well as all the other information about the video itself...

I'm opening this issue to let you know about it, if you dont know already, and to see if you have any ideia how to make it work :)

**Comment by nasirzid** [comment]
Hello Robert,

I am also facing the issue of music and Videos are not able to scrap and it returns the URL only. Please have a look at this and if you can fix it , that would be really good.

Thanks.

**Comment by RobertGrubb** [comment]
@AdrianoRamalho21 So the issue now is that they have changed the required headers for the URL (Referer and User-Agent). For instance, if you go to their site, load a video directly, then refresh it, it returns a 403 because you refreshed it directly without the required headers.

The scraper (`v1.7.4`) has been updated to provide these headers when downloading a video, so my suggestion is to make sure you download it from the scraper, instead of trying to access it directly. Up until now, the scraper wasn't working, but should be working fine now, just pull `v1.7.4`. @nasirzid -- Please read the last bit of info.

**Comment by nasirzid** [comment]
@RobertGrubb ,

Thanks a lot. The new version seems working for the endpoint (**musicVideos**) but i am facing issue when i hit multiple times the same end point. Sometimes it display data and sometimes it's not. Please have  a look at the video link below

https://www.loom.com/share/6e97ed4422254856a460353dd8566e80 

I believe that you can fix this issue too.

Thanks.

**Comment by yasirrose** [comment]
Hello Robert,

I am also facing issue for when scrapping musicVideos. If i hit 2-3 times the response will not come and it displays only the URL. But after trying 4-5 times it again works. Can you please look into this issue that why it happens?

Thanks

**Comment by RobertGrubb** [comment]
Hey, friends!

So the response you're seeing is actually a captcha response from TikTok. I am currently in the midst of trying to find a way around it. I'll let you know what I find. Other than that, the only thing I can really suggest is proxy rotation, etc.

**Comment by yasirrose** [comment]
Hey Robert,

Did you get any way to get TikTok response to avoid the captcha issue without Proxy?
@RobertGrubb

**Comment by RobertGrubb** [comment]
May I have you try this? https://github.com/RobertGrubb/tiktok-php/issues/28#issuecomment-700190214

**Comment by RobertGrubb** [comment]
Moving this to #28 for discussion.
