### ISSUE TITLE
Captcha Returning

### ISSUE THREAD

**Issue by andersonrobert1313** [RobertGrubb/tiktok-php#28]
When we try to fetch videos it is saying code 10000
when can you sort this ??
my project is live and customers are complaining me,
Thanks

**Comment by RobertGrubb** [comment]
Hey @andersonrobert1313 

Right now, the best solution I've found personally is to login to TikTok's website, grab the cookie header in any request made (In the request headers from the network tab in your browser console).

As of my recent release `v1.7.5`, you can pass `cookie` as a config parameter and use that cookie string I was talking about above. This will simulate a logged in session that will stop the captcha (from what I've tested, at least).

**Comment by andersonrobert1313** [comment]
Hi @RobertGrubb 
Thanks for your quick response.

You are saying to login to tiktok from api or from web ?
can you send any example of working code here.
How to get and send cookie parameter.
Thanks is advance.

**Comment by RobertGrubb** [comment]
Yeah so login to TikTok on a web browser. 

After, open your developer console, go to network, find a request like I'm going to show you in the following picture, and copy the cookie header under "Request Headers". After you copy it, in your code, you can set the cookie in the config of the scraper like so:

```
new Scraper([
  'cookie' => 'the string I told you to copy'
]);
```

<img width="1278" alt="Screen Shot 2020-09-28 at 1 46 38 PM" src="https://user-images.githubusercontent.com/13295554/94468476-78e41a80-0192-11eb-9ecb-1bb1b53c7ad4.png">

After, see if the captcha goes away. I've personally done this and it worked, but I can't vouch for any other setup than my own. So if it does, reply back and let me know either way.

**Comment by yasirrose** [comment]
@RobertGrubb 
Thanks for the suggestion but I have another question :
Will this work for multiple hits?
 and if the cookie expires how we can get a new cookie automatically using API instead of hardcoded?

**Comment by andersonrobert1313** [comment]
@RobertGrubb 

Thanks for your response.
I have an app in which customer can add their username and then i am fetching their videos and then customer can select or turn on any video from their profile they want to show on their profile page.
so can i use same cookie code for all of my customers .
i mean to say i can put cookie one time in code and it works lifeitime ?

**Comment by andersonrobert1313** [comment]
> Yeah so login to TikTok on a web browser.
> 
> After, open your developer console, go to network, find a request like I'm going to show you in the following picture, and copy the cookie header under "Request Headers". After you copy it, in your code, you can set the cookie in the config of the scraper like so:
> 
> ```
> new Scraper([
>   'cookie' => 'the string I told you to copy'
> ]);
> ```
> 
> <img alt="Screen Shot 2020-09-28 at 1 46 38 PM" width="1278" src="https://user-images.githubusercontent.com/13295554/94468476-78e41a80-0192-11eb-9ecb-1bb1b53c7ad4.png">
> 
> After, see if the captcha goes away. I've personally done this and it worked, but I can't vouch for any other setup than my own. So if it does, reply back and let me know either way.

@RobertGrubb yes this is working fine till now, but after certain time same issue occur,
because cookie expired.
so what is the best solution for this.
we can't add cookie again and again or we can't dynamic the cookie as well.

**Comment by RobertGrubb** [comment]
@andersonrobert1313 @yasirrose I am currently working on a way to do the cookie stuff programmatically. At the time of writing this, I'm about half way through the process. I should have something to release by midday tomorrow (eastern time).

**Comment by RobertGrubb** [comment]
I have made a new breaking change release `v1.8.1`.

Please refer to https://github.com/RobertGrubb/tiktok-php/pull/29 for more information on what has changed.

**Comment by andersonrobert1313** [comment]
@RobertGrubb 
Thanks Bro...this is working now.
can you make sure there is no api limitation on multiple requests.

**Comment by andersonrobert1313** [comment]
@RobertGrubb 
Hey Robert the issue is still there... it works first time if cookies files is empty then it write the cookies file...but if i come back after 10 minutes then it is again asking for captcha.

**Comment by RobertGrubb** [comment]
@andersonrobert1313 Will look into it more soon. Wondering if the webid cookie should be deleted after captcha is received then. Testing then will let you know.

**Comment by andersonrobert1313** [comment]
@RobertGrubb 
Okay thanks.
i am waiting for your response.

**Comment by RobertGrubb** [comment]
@andersonrobert1313 I've just released v1.8.2 (Give it time, composer's cache is sometimes a bit behind). 

However, I have added a block of code that will delete the currently stored cookies when captcha response is received. So what happens is, it will request their home page, get a new webid, and then on the next run it will attempt to use the newly stored cookies.

Let me know how that goes, I'm personally having a hard time to get the captcha response now on 3 different test servers, so one I hit it again, I'll be able to debug more. This update was more of just a "shot in the dark" to see if resetting fixes it. 

If it doesn't, I'll continue working on a solution once I get a bit more free time.

**Comment by andersonrobert1313** [comment]
@RobertGrubb 
Okay, let me update and check the response.
i"ll let you know,

**Comment by andersonrobert1313** [comment]
@RobertGrubb 
Hey man..it's working now correctly without any captcha response.
You are a rockstar!
Thanks Bro.

**Comment by RobertGrubb** [comment]
Alright, sounds good! I'll close this ticket now. However, if something happens again, feel free to open another!
