### ISSUE TITLE
Fatal error: failed to open stream: No such file or directory in __DIR__ . '/env.php'

### ISSUE THREAD

**Issue by sarabhi92git** [RobertGrubb/tiktok-php#31]
Hi @RobertGrubb , I am getting error failed to open stream: No such file or directory env.php

You set env.php in examples/videos.php and when I run that I get error env.php file not found.
/**
 * Get development config
 */
$config = require_once __DIR__ . '/env.php';

The file is not there as it is not present in your release.

**Comment by RobertGrubb** [comment]
It's not present on purpose. You need to create the `env.php` with the following:

```
<?php 

return [
  'cookiesFile' => __DIR__ . '/cookies.json'
];
```

Or you can instantiate the scraper like so:

```
new Scraper([
  'cookiesFile' => __DIR__ . '/cookies.json'
]);
```

All that's happening in those lines is including a config file.

**Comment by sarabhi92git** [comment]
Thank you so much @RobertGrubb !

I got the point.
