### ISSUE TITLE
captcha requiring for hashtag videos

### ISSUE THREAD

**Issue by andersonrobert1313** [RobertGrubb/tiktok-php#32]

**Comment by andersonrobert1313** [comment]
hello @RobertGrubb 
when i try to get videos by the following functions it is going to code 10000
even after cookies code updated.

1) $scraper->hashtag->data($request->hashtag);
2) $dataa = $scraper->hashtag->videos($request->hashtag,20);

no. 1 is working fine, but no.2 is asking for captcha,
can you sort this ?

**Comment by andersonrobert1313** [comment]
> hello @RobertGrubb
> when i try to get videos by the following functions it is going to code 10000
> even after cookies code updated.
> 
> 1. $scraper->hashtag->data($request->hashtag);
> 2. $dataa = $scraper->hashtag->videos($request->hashtag,20);
> 
> no. 1 is working fine, but no.2 is asking for captcha,
> can you sort this ?

Hello @RobertGrubb 
can you plz reply me ?

**Comment by RobertGrubb** [comment]
Have you tried this on `v1.9.1`? Recently a few changes come into play from their platform, seeing if this has changed anything.

**Comment by andersonrobert1313** [comment]
Thanks..it works now.

**Comment by andersonrobert1313** [comment]
hey ,
fetch data for single video is always returning empty,
can you plz chek asap.
$data = $scraper->user->video($tiktok->username,$tiktok->video_id);
thanks
