### ISSUE TITLE
User data not getting

### ISSUE THREAD

**Issue by andersonrobert1313** [RobertGrubb/tiktok-php#37]
when try to get user data
error : 
Array ( [error] => 1 [message] => Unable to retrieve NEXT_DATA from DOM )

**Comment by RobertGrubb** [comment]
This is due to the captcha verification coming back as a response. Right now, there's not a solid solution for this, so what I'll be doing is pushing an update that allows you to manually set the `verifyFp` token. Stay tuned.

**Comment by SlavaPWNZ** [comment]
> This is due to the captcha verification coming back as a response. Right now, there's not a solid solution for this, so what I'll be doing is pushing an update that allows you to manually set the `verifyFp` token. Stay tuned.

Hey Robert! I often get code 10000 or error 'Verification for current cookie data is required'. It also looks like captcha...

**Comment by yasirrose** [comment]
When I hit any file like video.php, music.php, or any other file to get data I am also facing such type of sam error in the response. Please have a look at the screenshot.
![image](https://user-images.githubusercontent.com/5586359/99258550-8cc70700-283a-11eb-87da-91ab7c163b69.png)

**Comment by andersonrobert1313** [comment]
Hey @RobertGrubb 
when can you push the new updates ?
i am using your library on my live site and my customers are complaining.
can you provide the stable version.
Thanks

**Comment by RobertGrubb** [comment]
@andersonrobert1313 

As of `v1.9.12` you may now manually set a `fp` token that you have verified via captcha from tiktok's website like so:

```
$scraper = new Scraper([
  'verifyFp' => 'verify_xxxxxx_xxx...'
]);
```

As soon as it's possible, I will implement a captcha solver. Just not sure about the route I want to take with it yet.

**Comment by RobertGrubb** [comment]
Closing due to no response. Feel free to reopen if need be.

**Comment by andersonrobert1313** [comment]
Hey @RobertGrubb 
This is not the solution i can't tell to all my customers for go to tiktok website and add the manually token.
Do you have any other solution for this.

**Comment by RobertGrubb** [comment]
> Hey @RobertGrubb 
> This is not the solution i can't tell to all my customers for go to tiktok website and add the manually token.
> Do you have any other solution for this.

I'm not sure what your setup is. If you're saying that you spin up a new scraper for every customer, then yes, this is the actual solution right now. 

If you are scraping FOR your customers, only you should be setting the fp token on your scraper configuration.

**Comment by andersonrobert1313** [comment]
Hey @RobertGrubb

I am using your library on shopify app.
So all my customers are using my app on their store.
So each store has their own username and own platform to use your apis.

So in my app there is an input field by saying enter tiktok username.

Once  they add username then I'll hit your apis and fetch last 20 videos.
From those videos customer can on/off what to show or hide on their website.

Now can you let me know how can I continue with your apis.

Thanks

**Comment by findtvseries** [comment]
Tiktok / Libraries / Request.php Line  309 
"
  if (preg_match_all('#\<script id=\"__NEXT_DATA__\" type=\"application/json\" crossorigin=\"anonymous\">(.*?)\<\/script\>#', $this->data, $out)) {
      return json_decode($out[1][0], true, 512, JSON_BIGINT_AS_STRING);
    }
"
change code
"
    if (preg_match_all('#\<script id=\"__NEXT_DATA__\" type=\"application/json\" nonce="(.*?)" crossorigin=\"anonymous\">(.*?)\<\/script\>#', $this->data, $out)) {
	
      return json_decode($out[2][0], true, 512, JSON_BIGINT_AS_STRING);
    }
"
Tadadadam
