### ISSUE TITLE
tiktok-verify-page

### ISSUE THREAD

**Issue by SlavaPWNZ** [RobertGrubb/tiktok-php#38]
when i got captcha, im trying do:
$data = $this->scraper->captcha->setFp()->get()->solve();

but No s_v_web_id cookie found

$scraper = new Scraper([
                'signMethod' => 'node',
                'datafetchApiKey' => '',
                'timeout' => 200,
                'verbose' => false,
                //'verifyFp' => 'verify_khq85fui_tzRbKrID_W8rL_4Jq2_AfMt_OgwBbY7bS9y8',
                //'disableCookies' => true,
                'cookieFile' => $filename,
                'userAgent' => static::$_instance->useragent,
                'proxy' => static::$_instance->proxy,
            ]);

**Comment by RobertGrubb** [comment]
Hey there. The captcha methods are still being developed. So right now they will fail. Ive purposely left them out of the documentation for that reason. I apologize for the confusion.

**Comment by SlavaPWNZ** [comment]
> Hey there. The captcha methods are still being developed. So right now they will fail. Ive purposely left them out of the documentation for that reason. I apologize for the confusion.

Can i help u? You can contact me and I can take on part of the tasks to solve the problem with captcha
