### ISSUE TITLE
scrape

### ISSUE THREAD

**Issue by andrewem** [RobertGrubb/tiktok-php#9]
Hi,

I'm looking to get followings or followers of a specified tiktok users and save the results in notepad or excel.

Is that possible with your tiktok scrapper?

**Comment by RobertGrubb** [comment]
At the moment this is not possible with the current version, but will look later on to see if i can manage it with the web platform. Will circle back

**Comment by RobertGrubb** [comment]
I have not found a route from the website itself to get following/followers. Going to tag this as a `review-in-future` just incase they add one. Will close for now.
